server.port: 3001
spring:
  application:
    name: user-service
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        #healthCheckPath: /my-health-check
        #healthCheckInterval: 20s
        enabled: true
        instanceId: ${spring.application.name}:${random.value}
